#Multi Stage Dockerfile https://spring.io/guides/topicals/spring-boot-docker/

ARG SERVICE=gateway

#1st Stage: Building the image
FROM maven:3.8.6-eclipse-temurin-17-alpine as build
WORKDIR /opt/app
ARG SERVICE

COPY . .

RUN mvn install -pl ${SERVICE} -am -DskipTests
RUN mkdir -p ${SERVICE}/target/dependency && (cd ${SERVICE}/target/dependency; jar -xf ../*.jar)

#2nd Stage: Running the image
FROM eclipse-temurin:17-jdk-alpine
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
VOLUME /tmp
ARG SERVICE
ARG DEPENDENCY=/opt/app/${SERVICE}/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app

ENTRYPOINT ["java","-cp","app:app/lib/*","com.sportscentre.GatewayApplication"]
